"""empty message

Revision ID: 66dc9055ce55
Revises: 
Create Date: 2024-11-30 20:35:44.815000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dc9055ce55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulltime',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('locatedat',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id', 'job_id')
    )
    op.create_table('fulltime_benefits',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('benefit', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['fulltime.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'benefit')
    )
    op.drop_table('fullTime')
    op.drop_table('fullTime_benefits')
    op.drop_table('locatedAt')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.Date(), nullable=False))
        batch_op.drop_constraint('FK__applicati__jobId__4D94879B', type_='foreignkey')
        batch_op.drop_constraint('FK__applicati__email__4CA06362', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['email'], ['email'], ondelete='CASCADE')
        batch_op.drop_column('applicationId')
        batch_op.drop_column('additionalNotes')
        batch_op.drop_column('createdDate')
        batch_op.drop_column('jobId')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('companyId')

    with op.batch_alter_table('contains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interview_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('FK__contains__applic__571DF1D5', type_='foreignkey')
        batch_op.drop_constraint('FK__contains__interv__5812160E', type_='foreignkey')
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['application_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'interview', ['interview_id'], ['interview_id'], ondelete='CASCADE')
        batch_op.drop_column('applicationId')
        batch_op.drop_column('interviewId')

    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hourly_pay', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.drop_constraint('FK__internshi__jobId__440B1D61', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
        batch_op.drop_column('hourlyPay')
        batch_op.drop_column('startDate')
        batch_op.drop_column('endDate')
        batch_op.drop_column('jobId')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('round_type', sa.String(length=50), nullable=False))
        batch_op.drop_constraint('FK__interview__appli__5070F446', type_='foreignkey')
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['application_id'], ondelete='CASCADE')
        batch_op.drop_column('applicationId')
        batch_op.drop_column('roundType')
        batch_op.drop_column('interviewId')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('FK__job__companyId__3E52440B', type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['company_id'], ondelete='CASCADE')
        batch_op.drop_column('companyId')
        batch_op.drop_column('jobTitle')
        batch_op.drop_column('jobId')

    with op.batch_alter_table('job_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('FK__job_locat__jobId__412EB0B6', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
        batch_op.drop_column('jobId')

    with op.batch_alter_table('submits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('FK__submits__email__534D60F1', type_='foreignkey')
        batch_op.drop_constraint('FK__submits__applica__5441852A', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['email'], ['email'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'application', ['application_id'], ['application_id'], ondelete='CASCADE')
        batch_op.drop_column('applicationId')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_year', sa.Integer(), nullable=False))
        batch_op.drop_column('classYear')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classYear', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('class_year')

    with op.batch_alter_table('submits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicationId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__submits__applica__5441852A', 'application', ['applicationId'], ['applicationId'])
        batch_op.create_foreign_key('FK__submits__email__534D60F1', 'user', ['email'], ['email'])
        batch_op.drop_column('application_id')

    with op.batch_alter_table('job_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__job_locat__jobId__412EB0B6', 'job', ['jobId'], ['jobId'])
        batch_op.drop_column('job_id')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('jobTitle', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__job__companyId__3E52440B', 'company', ['companyId'], ['companyId'], ondelete='CASCADE')
        batch_op.drop_column('job_title')
        batch_op.drop_column('company_id')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interviewId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('roundType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('applicationId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__interview__appli__5070F446', 'application', ['applicationId'], ['applicationId'])
        batch_op.drop_column('round_type')
        batch_op.drop_column('application_id')
        batch_op.drop_column('interview_id')

    with op.batch_alter_table('internship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('hourlyPay', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__internshi__jobId__440B1D61', 'job', ['jobId'], ['jobId'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('hourly_pay')
        batch_op.drop_column('job_id')

    with op.batch_alter_table('contains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interviewId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('applicationId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__contains__interv__5812160E', 'interview', ['interviewId'], ['interviewId'])
        batch_op.create_foreign_key('FK__contains__applic__571DF1D5', 'application', ['applicationId'], ['applicationId'])
        batch_op.drop_column('interview_id')
        batch_op.drop_column('application_id')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('createdDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('additionalNotes', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('applicationId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__applicati__email__4CA06362', 'user', ['email'], ['email'])
        batch_op.create_foreign_key('FK__applicati__jobId__4D94879B', 'job', ['jobId'], ['jobId'])
        batch_op.drop_column('created_date')
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('job_id')
        batch_op.drop_column('application_id')

    op.create_table('locatedAt',
    sa.Column('companyId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companyId'], ['company.companyId'], name='FK__locatedAt__compa__5AEE82B9'),
    sa.ForeignKeyConstraint(['jobId'], ['job.jobId'], name='FK__locatedAt__jobId__5BE2A6F2'),
    sa.PrimaryKeyConstraint('companyId', 'jobId', name='PK__locatedA__3C30F38A702CB80F')
    )
    op.create_table('fullTime_benefits',
    sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('benefit', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['fullTime.jobId'], name='FK__fullTime___jobId__49C3F6B7'),
    sa.PrimaryKeyConstraint('jobId', 'benefit', name='PK__fullTime__85C4DC57B1F74EE7')
    )
    op.create_table('fullTime',
    sa.Column('jobId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['job.jobId'], name='FK__fullTime__jobId__46E78A0C'),
    sa.PrimaryKeyConstraint('jobId', name='PK__fullTime__164AA1A884CFEE6D')
    )
    op.drop_table('fulltime_benefits')
    op.drop_table('locatedat')
    op.drop_table('fulltime')
    # ### end Alembic commands ###
